services:
  # ğŸ¦“ Zookeeper
  zookeeper-server:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper-server
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  # ğŸ¦’ Kafka Broker
  kafka-server:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka-server
    restart: always
    depends_on:
      - zookeeper-server
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-server:2181"
      # âœ… Kafka å…§å¤–é›™é€šç”¨
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      # âœ… Console ç”¨ INTERNALï¼›å¤–éƒ¨ ngrok ç”¨ EXTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-server:29092,EXTERNAL://192.168.5.49:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  # ğŸ¼ Redpanda Console
  redpanda-console-server:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console-server
    restart: always
    depends_on:
      - kafka-server
    ports:
      - "19900:8080"
    environment:
      # âœ… é€™è£¡åªè¦å¡«å®¹å™¨å…§éƒ¨ä½å€
      KAFKA_BROKERS: kafka-server:29092
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

